# syntax=docker/dockerfile:1
FROM python:3.12-slim

WORKDIR /app

COPY requirements.etl.txt .
RUN pip install --no-cache-dir -r requirements.etl.txt

COPY . .

ENV DBT_PROFILES_DIR=/app/.dbt

CMD ["python", "-m", "orchestration.etl"]